/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TestIndexImport } from './routes/test/index'
import { Route as StoreIndexImport } from './routes/store/index'
import { Route as ServiceIndexImport } from './routes/service/index'
import { Route as AccountIndexImport } from './routes/account/index'
import { Route as StoreIdImport } from './routes/store/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestIndexRoute = TestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any)

const StoreIndexRoute = StoreIndexImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRoute,
} as any)

const ServiceIndexRoute = ServiceIndexImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIndexRoute = AccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const StoreIdRoute = StoreIdImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/service/': {
      id: '/service/'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceIndexImport
      parentRoute: typeof rootRoute
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreIndexImport
      parentRoute: typeof rootRoute
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/store/$id': typeof StoreIdRoute
  '/account': typeof AccountIndexRoute
  '/service': typeof ServiceIndexRoute
  '/store': typeof StoreIndexRoute
  '/test': typeof TestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/store/$id': typeof StoreIdRoute
  '/account': typeof AccountIndexRoute
  '/service': typeof ServiceIndexRoute
  '/store': typeof StoreIndexRoute
  '/test': typeof TestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/store/$id': typeof StoreIdRoute
  '/account/': typeof AccountIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/store/': typeof StoreIndexRoute
  '/test/': typeof TestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/store/$id' | '/account' | '/service' | '/store' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/store/$id' | '/account' | '/service' | '/store' | '/test'
  id:
    | '__root__'
    | '/'
    | '/store/$id'
    | '/account/'
    | '/service/'
    | '/store/'
    | '/test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreIdRoute: typeof StoreIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  TestIndexRoute: typeof TestIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreIdRoute: StoreIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  ServiceIndexRoute: ServiceIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  TestIndexRoute: TestIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/store/$id",
        "/account/",
        "/service/",
        "/store/",
        "/test/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/store/$id": {
      "filePath": "store/$id.tsx"
    },
    "/account/": {
      "filePath": "account/index.tsx"
    },
    "/service/": {
      "filePath": "service/index.tsx"
    },
    "/store/": {
      "filePath": "store/index.tsx"
    },
    "/test/": {
      "filePath": "test/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
